{% set version = "8.0" %}

package:
  name: readline
  version: {{ version }}

source:
  url: ftp://ftp.gnu.org/gnu/readline/readline-{{ version }}.tar.gz
  sha256: e339f51971478d369f8a053a330a190781acb9864cf4c541060f12078948e461

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 2
{% endif %}
  skip: true  # [win]
  run_exports:
    # change soname at major ver: https://abi-laboratory.pro/tracker/timeline/readline/
    - {{ pin_subpackage('readline') }}
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
{% if bootstrapping != 'yes' %}
    - pkg-config
    - make
    - libtool
  host:
    - ncurses
  run:
    - ncurses
{% endif %}

test:
  commands:
  {% set readline_libs = [
    'libreadline',
    'libhistory'
  ] %}
  {% for lib in readline_libs %}
    - test ! -f ${PREFIX}/lib/{{ lib }}.a
    - test -f ${PREFIX}/lib/{{ lib }}${SHLIB_EXT}  # [not win]
  {% endfor %}

about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL-3.0-only
  license_file: COPYING
  summary: library for editing command lines as they are typed in

extra:
  recipe-maintainers:
    - croth1
    - jakirkham
    - jjhelmus
    - pelson
    - msarahan
    - asmeurer
    - msarahan
    - mingwandroid
    - ocefpaf
